### PR TITLE
Feature/backend

### PR DESCRIPTION
**Pull request by Faizan-omer**
- Added post event api
- Added test for api

### CODE REVIEW

**Review by hparashar27 — COMMENTED** [review]
okay its great , @Faizan-omer i am getting an error on running md-seed run command , can you tell me how to cope with it 
Code_RHMErpX5MS

**Comment by Faizan-omer** [comment]
@hparashar27 try installing 'mongoose-data-seed' globally using `npm i -g mongoose-data-seed` that will resolve the issue

**Comment by Faizan-omer** [comment]
let me know if more api's are required I can start working on them

**Comment by hparashar27** [comment]
@Faizan-omer sure i will let you know for more apis

**Pull request merged**
